project:
  type: website
  output-dir: docs

website:
  title: "BIO 5800L"
  site-url: https://claisselab.github.io/BIO_5800L
  back-to-top-navigation: true

  # Provides links to the source files beside the table of contents
  repo-url: https://github.com/ClaisseLab/BIO_5800L
  repo-actions: [source]

  navbar:
    background: primary
    pinned: true
    search: true

    left:
      - text: "Resources"
        href: index.qmd
      - text: "Funding Sources"
        href: Funding_Sources.qmd
      - text: "BIO 5100"
        href: https://claisselab.github.io/BIO_5100/

    tools:
      - icon: house-fill
        href: https://claisselab.com
        aria-label: "Claisse Lab website"
      - icon: github
        href: https://github.com/ClaisseLab/BIO_5800L
        aria-label: "BIO 5800L GitHub repository"

  page-footer:
    left: "Claisse BIO Course Resources"
    right: "Built with [Quarto](https://quarto.org/)"

format:
  html:
    theme:
      light: flatly
      dark: darkly
    respect-user-color-scheme: true
    css: styles.css
    toc: true
    smooth-scroll: true
    link-external-icon: true
    link-external-newwindow: true

editor: visual
