---
title: "Funding Sources"
---

## Student Tuition/Living Expenses Funding

#### [Financial Aid through FASFA process via CPP (to apply for Cal Grant + work study)](https://www.csac.ca.gov/fafsa)

-   **All grad students should submit a [FASFA application](https://www.csac.ca.gov/fafsa)** every spring (starting the year you are applying to the CPP Masters program)
-   Many students get the "Cal Grant" which covers 2 years of full time tuition for the masters program.
-   You should also **"check the work-study box"** to indicate you want to be considered for work study funds (and potentially get paid to work in your lab doing your thesis research)
-   You'll get an financial aid offer package and then you can choose what to accept/reject (e.g., you don't have to accept student loans if you don't want them)

#### [CPP Biology Dept. Scholarships (**you all should apply every spring**)](https://www.cpp.edu/sci/biological-sciences/students/student-scholarships.shtml)

-   Grad students should apply for 3 scholarships every spring.

## (sub-field specific) Student Research/Tuition/Expenses Funding

#### [CSU COAST - Graduate Student Research Awards (Marine/Coastal Research Focus)](https://www.calstate.edu/impact-of-the-csu/research/coast/students/Pages/default.aspx)

-   Marine/Coastal research focused students should also sign up for the [**student email list**](https://www.calstate.edu/impact-of-the-csu/research/coast/Pages/student-sign-up.aspx) (e.g., get announcements about funding, fellowships, jobs, internships)
-   You can apply annually for funding for field experiences/gear, travel to conferences, and your research/living expenses.

#### [Nancy Foster Scholarship Program](https://fosterscholars.noaa.gov/)

#### [Garden Club of America Award in Coastal Wetlands Studies](https://www.gcamerica.org/scholarships/details/id/11)

#### [Women Divers Hall of Fame Scholarships](https://www.wdhof.org/scholarships/scholarship-descriptions)

#### [Phycological Society of America - Croasdale Fellowship (for taking a phycology course at biological field stations)](https://www.psaalgae.org/croasdale-award)

#### [Phycological Society of America - Grants-in-aid research program](https://www.psaalgae.org/grantsinaid-of-research)

#### [Rafe Sagarin Fund for Innovative Ecology](https://rafeinnovativeecologyfund.org/apply/)

## Travel Funding (for presenting your research at conferences)

#### [CPP - OUR Conference Presentation Scholarship](https://www.cpp.edu/our-cpp/students/conference-award/application.shtml)

-   (Office of Undergraduate Research - but grad students are eligible - and have been very successful at getting conference travel funds)

#### [CSUPERB Biotech Student Travel Grant Program (And other CSUPERB funding programs](https://www.calstate.edu/impact-of-the-csu/research/csubiotech/Pages/grants-and-awards-programs.aspx)

#### [CSU COAST - Student Travel Awards (Marine/Coastal Research Focus)](https://www2.calstate.edu/impact-of-the-csu/research/coast/funding/Pages/student-funding.aspx)

#### [CPP Project LOGRAR Grad Student Travel Stipend](https://www.cpp.edu/grc/resources-and-opportunities/funded-opportunities.shtml)

#### *& most conferences have their own student travel funding, so check out their website*

## Fellowship Programs (for current students and after you graduate):

#### [California Sea Grant State Fellowships](https://caseagrant.ucsd.edu/students/fellowships)
-   various programs for (marine oriented) current students, and for right after you graduate

#### [Switzer Foundation Fellowship](https://www.switzernetwork.org/become-fellow)

#### [Seagrant Knauss Fellowship](https://seagrant.noaa.gov/Prospective/#289216-who-is-eligible-for-the-knauss-fellowship)
-   Go work in Washington DC as a policy specialist applying your scientific expertise right after your graduate

#### [Margaret Davidson Graduate Fellowship](https://coast.noaa.gov/nerrs/research/davidson-fellowship.html?utm_medium=email&utm_source=GovDelivery)
