---
title: "BIO 5800L Resources"
---

## [Funding Sources Page](https://claisselab.github.io/BIO_5800L/Funding_Sources.html)

## Literature Search & Citing

#### [Connect your Google Scholar to CPP Library to access pdfs of journal articles](https://libguides.library.cpp.edu/c.php?g=863498&p=6191577)

-   Link your CPP library account to your google scholar

#### [Zotero Reference Managment Software](https://www.zotero.org/)

-   Zotero is a free, easy-to-use tool to help you collect, organize, annotate, create and format in-text citations and literature cited list in your documents.

#### [How to appropriately cite R and R packages](https://ropensci.org/blog/2021/11/16/how-to-cite-r-and-r-packages/)

-   A short primer from a popular R blog on how to cite R and R packages in your thesis, publications, etc.

## Scientific Writing

#### [Turbek et al. 2016. **Scientific Writing Made Easy: A Step-by-Step Guide to Undergraduate Writing in the Biological Sciences.** Bull Ecol Soc Am, 97: 417-426.](https://esajournals.onlinelibrary.wiley.com/share/2CMJAIKAAZ2VRPTBZNIP?target=10.1002/bes2.1258)

-   A straightforward guide to writing each section of a thesis/paper. While originally conceived for undergrads, it is also great for grad students.

#### [Davis and Kay. 2023. **Writing Statistical Methods for Ecologists.** Ecosphere 14(5): e4539](https://esajournals.onlinelibrary.wiley.com/doi/full/10.1002/ecs2.4539)

-   They provide guidelines for researchers when writing statistical methods and review frequent errors made in Statistical Methods sections. They highlight common **dos and don'ts** when writing Statistical Methods sections and present a simple checklist to help guide authors with their writing to ensure reproducibility.

#### [Muff et al. 2022. Rewriting results sections in the language of evidence, Trends in Ecology & Evolution, 37:3, p 203-210](https://esajournals.onlinelibrary.wiley.com/doi/full/10.1002/ecs2.4539)

-   Language matters and ‘evidence’ is an intuitive concept that honestly reflects what the data really tell us. To facilitate rewriting scientific results, we offer generic examples of how to translate significance language into a gradual language of evidence you can use when writing results sections.

#### [Duke Graduate School Scientific Writing Resource](https://sites.duke.edu/scientificwriting/)

-   Intended for science students at the graduate level, this online course material teaches how to write effectively. It is not about correctness (grammar, punctuation, etc.), but about communicating what you intend more clearly to the reader. 

#### [Methods section too short? Use online protocols to make complex techniques understandable](https://www.nature.com/articles/d41586-023-03249-2)

-   Looking for a method protocol? Check out this article for where to find published versions.

-   Develop a method protocol as part of your thesis? Consider publishing it in a peer-reviewed journal.

-   Some protocols, such as those published on [Nature Protocol Exchange](https://www.nature.com/nprot/protocolexchange), Cell Press's [STAR Protocols](https://www.cell.com/star-protocols/home), [PLOS Lab Protocols](https://collections.plos.org/collection/lab-protocols/) and [Bio-protocol](https://bio-protocol.org/en), are hosted by journal publishers, but there are other options, including [Protocols.io](https://www.protocols.io/) and [OpenWetWare.org](https://openwetware.org/wiki/Main_Page).

## Scientific Posters

#### [How to create a better research poster in less time (Generation 1 Video)](https://www.youtube.com/watch?v=1RwJbhkCA58)

#### [How to create a better research poster in less time (Generation 2 Video - explains the science behind effective communication w/ posters)](https://www.youtube.com/watch?v=SYk29tnxASs)

-   **Stop creating posters that are walls of text (that nobody will ever read) and create more effective communication tools in less time...**
-   [PPT poster TEMPLATES](https://osf.io/6ua4k/)

## Using Canvas (as an instructor)

#### [2 hr video tutorial on using Canvas as an instructor (Linkedin Learning)](https://www.linkedin.com/learning/learning-canvas-2021/create-and-manage-courses-with-canvas?u=56973593)

#### [CPP training and support links for Canvas)](https://www.cpp.edu/cafe/teaching-and-learning/lms-support/index.shtml)

## Being a Mentor

#### [Emery et al. 2019. Strategies for successful mentorship of undergraduate researchers. Ecol Evol. 9: 4316--4326.](https://onlinelibrary.wiley.com/doi/full/10.1002/ece3.5090)

-   As graduate students mentoring undergrad researchers in your lab is an important experience to get for any career path you are interested in (and something you should put on your CV). Whether you are interviewing for PhD programs, for a job in a biotech company or an environmental consulting firm, you should be prepared to describe your experience in the critical skill of training and managing others. This paper provides guidance on how to be a good mentor.

#### [Markle et al. 2022. Supporting Historically Underrepresented Groups in STEM Higher Education: The Promise of Structured Mentoring Networks. Frontiers in Education 7.](https://www.frontiersin.org/articles/10.3389/feduc.2022.674669/full)

-   Additional guidance for mentoring URM students.

## General Grad School Advice & Time Management

#### [Nine tips for managing time in grad school (ASBMB Article)](https://www.asbmb.org/asbmb-today/careers/081722/nine-tips-for-managing-time-in-grad-school?)

#### [What Not to Do in Grad School (Nature.com PDF Download)](https://livecsupomona-my.sharepoint.com/:b:/g/personal/jtclaisse_cpp_edu/EZJlZBWa5q9Mu0PQZW7ZI18B5hsn-FhSp3JYiHXMY8l5aw?e=bFImvC)

#### [How I developed sustainable work habits in academia (Science Magazine Blog Post)](https://www.science.org/content/article/how-i-developed-sustainable-work-habits-in-academia)

#### [Why I use Notion to organize my PhD research (Comentary in Nature)](https://www.nature.com/articles/d41586-023-03323-9)

-   A big part of a masters or PhD program is developing (often through trial and error) your "process" for managing your time, projects and the important information and resources related to your research and other aspects of your work.  
-   [Notion](https://www.notion.so/) is a free, all-in-one workspace for note-taking, project management and task management.

## Email

#### [Inbox Zero Method 101: How to Master It](https://missiveapp.com/blog/inbox-zero)

#### [email Etiquette (UCLA Graduate Writing Center Video)](https://youtu.be/ZPFxP2HDR8s?si=L8M0lLgOK8ugKCT7)


## Career Advice/Perspectives

#### [Podcast: The World of Scientists (CPP grad student produced)](https://anchor.fm/world-of-scientists)

-   Can click on the Apple Podcasts, Spotify, or Google Podcasts icons on this website or you can listen directly from this link
-   Interviews with CPP Biology Faculty and staff about their career paths etc.

## Applying to PhD programs

#### [Estien et al. 2023. **Demystifying the Graduate School Application Process.** Bull Ecol Soc Am 104(1):e02029.](https://esajournals.onlinelibrary.wiley.com/doi/10.1002/bes2.2029)

-   Navigating the graduate school application process is often challenging, requiring intricate knowledge of academia and graduate institutional structures. This "Hidden Curriculum of Academia" includes what different graduate degrees offer, how to connect with a faculty member of interest, and the skills needed to submit a "competitive" application.

#### [(PDF download) A guide for applying to graduate school in Biology (Written by The German Lab, Dept. of Ecology & Evolutionary Biology, UC Irvine)](https://t.co/64nybx1Nlv)

-   To provide a guideline for prospective and current graduate students who might not know how to navigate the process. Expose what they don't tell you and provide tips and advice on applying to graduate school.

#### [(PDF download) Some Advice for Prospective Graduate Students (from a PI's perspective)](https://livecsupomona-my.sharepoint.com/:b:/g/personal/jtclaisse_cpp_edu/EVLTQlWIjwpHs0_MZK1xdtEBIFXrYM0sIA9iCqDlgDJwQg?e=u1GJAq)

-   Here's some advice from a professor about applying to their lab, but generally applicable.

#### [(PDF download) Applying to PhD programs timeline for the year you are applying (from a current PhD student's perspective)](https://livecsupomona-my.sharepoint.com/:b:/g/personal/jtclaisse_cpp_edu/ESf8kREGe8BJhT-4ph0Xg-0B7HfheHnzewmzMgzmTH9qpw?e=urvE2A)

-   Written by a current PhD student, here's their advice on a timeline and strategy for applying to PhD programs.
-   Note - GRE scores are being removed as a requirement for many programs, so check that for programs you are considering applying before you start studying

## Research/Job/Career email lists (list-serves)

#### [CSUBIOTECH Newsletter](https://www.calstate.edu/impact-of-the-csu/research/csubiotech/Pages/CSUBIOTECH-Newsletter-Sign-Up-Form.aspx)

-   Monthly newsletter includes updates and opinions on biotech education, entrepreneurship, research and workforce development. Often have seminars/workshops with biotech industry professionals.

#### [CSU COAST studnt eamil list](https://www.calstate.edu/impact-of-the-csu/research/coast/Pages/student-sign-up.aspx)

-   Student email list sends out periodic emails from CSU COAST about funding, internship and job opportunities related to coastal research, conservation and management.

#### [(ESA)Ecological Society of America aka "Ecolog-L" email list](https://www.esa.org/membership/ecolog/)

-   Ecolog-L is a list-serv that is a great resource for job postings, conference announcements, and other opportunities in the field of ecology. You can subscribe to the list-serv and have the emails sent to your inbox.

#### [Coral-List](https://lists.coralreefs.org/mailman/listinfo/coral-list/)

- email list focused on coral reef research and conservation

#### [Multiple Marine Conservation & Managment lists here](https://octogroup.org/)

-   The Ocean Conservation, Research, and Education Network (OCTO) has a number of email lists that you can subscribe to. These lists are a great resource for job postings, conference announcements, and other opportunities in the field of marine conservation and management.

#### And for others more focused on your sub-field ask your advisor!


## Applying for Federal Jobs

#### [4 Tips To Write An Effective Federal Resume (Youtube Video)](https://www.youtube.com/watch?v=KS5hxHJVCPk)
#### [Guidance for Applying for Federal Gov't Jobs (Youtube Channel)](https://www.youtube.com/channel/UCAGtfAdoxif6an9xM6YUIAQ)

-   There are videos in this feed about how to develop a "Resume" for a federal job application.
-   If working for the Fed Gov't is one of your potential career paths, then make sure you are including the information they ask for on your CV you are creating for 5800L, then it will be there when you go to create a more tailored CV/Resume for a Fed Job Application.

#### [Federal "Resumes": What You Should Know](https://www.usajobs.gov/Help/faq/application/documents/resume/what-to-include/)

-   (text below is from email list: *U.S. Fish & Wildlife Service Vacancy Announcements!*)
-   *Forget what you have heard about limiting your résumé to only 1 or 2 pages. Federal résumés must be comprehensive to include all the required information and to provide a robust résumé that will ensure you are among the best qualified for a position. (link above to webpage w/ tips and videos in link above that)*
-   *Although there is no reason to limit yourself to 1 or 2 pages, (it is most important to demonstrate to Human Resources that you meet the qualifications and have enough experience that will rank you among the best qualified), keep in mind that almost no hiring manager prefers reading a 20 page résumé. So, do not unnecessarily lengthen your résumé for the sake of showing every skill or experience you've ever had. Demonstrate relevant experience adequately, and pare down irrelevant experience.*
